GET http://localhost:5000

###
GET http://localhost:5000/products/

###
POST http://localhost:5000/products/

###
GET http://localhost:5000/products/20

###
GET http://localhost:5000/orders/

###
POST http://localhost:5000/orders/

###
GET http://localhost:5000/orders/20